version: '2'
services:
    trufflesampleapplication-app:
        image: trufflesampleapplication
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://trufflesampleapplication-mariadb:3306/trufflesampleapplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    trufflesampleapplication-mariadb:
        extends:
            file: mariadb.yml
            service: trufflesampleapplication-mariadb
